import type { Metadata } from "next";
import localFont from "next/font/local";
import dynamic from "next/dynamic";
import "./globals.css";
import NavBar from "../components/navbar";
import { HEADER_QUERY } from "./lib/queries";
import { client } from "./lib/client";
const Navbar = dynamic(() => import('../components/navbar'))
const Footer = dynamic(() => import('../components/footers'))

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const montserrat = localFont({
//   src: "./assets/fonts/Montserrat-VariableFont_wght.ttf", // Relative path is fine if correct
//   variable: "--font-montserrat",
// });

// const italic = localFont({
//   src: "./assets/fonts/Montserrat-Italic-VariableFont_wght.ttf",
//   variable: "--font-italic",
// })

export default async function RootLayout({
  children,
}: {
  
  children: React.ReactNode;
}) {
  const sections = await client.fetch(HEADER_QUERY);
  return (
    <html lang="en">
      <body className={` antialiased`}>
      <NavBar sections={sections}/>
        {children}
      <Footer/>
      </body>
    </html>
  );
}
